name: Latest blog post workflow
on:
  schedule:
    # Runs every hour
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          max_post_count: "4"
          feed_list: "https://medium.com/@kayodeatoyebi/feed"
      - name: Debug info
        run: |
          echo "Debug info: Showing git status"
          git status
          echo "Debug info: Showing current directory"
          ls -la
      - name: Commit and push changes
        env:
          GH_TOKEN: ${{ secrets.ALX_TOKEN }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          if git status --porcelain | grep '^[^?]'; then
            echo "Changes detected, committing and pushing..."
            git commit -m "Updated with the latest blog posts"
            git push https://${GH_TOKEN}@github.com/holufred/holufred.git HEAD:main
            echo "Pushed changes successfully!"
          else
            echo "No changes detected, nothing to commit or push."
          fi
